import { Router } from "express";

const router = Router();

const tools = [
  {
    id: "merge",
    name: "Merge PDF",
    description: "Combine multiple PDF files into one document",
    icon: "Combine",
    category: "Organize",
    route: "/merge",
    acceptedFormats: [".pdf"],
    outputFormat: "PDF",
  },
  {
    id: "split",
    name: "Split PDF",
    description: "Separate a PDF into individual pages or page ranges",
    icon: "Scissors",
    category: "Organize",
    route: "/split",
    acceptedFormats: [".pdf"],
    outputFormat: "ZIP",
  },
  {
    id: "compress",
    name: "Compress PDF",
    description: "Reduce PDF file size while maintaining quality",
    icon: "Minimize2",
    category: "Organize",
    route: "/compress",
    acceptedFormats: [".pdf"],
    outputFormat: "PDF",
  },
  {
    id: "rotate",
    name: "Rotate PDF",
    description: "Rotate pages in your PDF to the correct orientation",
    icon: "RotateCw",
    category: "Organize",
    route: "/rotate",
    acceptedFormats: [".pdf"],
    outputFormat: "PDF",
  },
  {
    id: "watermark",
    name: "Add Watermark",
    description: "Stamp a text watermark on your PDF pages",
    icon: "Stamp",
    category: "Organize",
    route: "/watermark",
    acceptedFormats: [".pdf"],
    outputFormat: "PDF",
  },
  {
    id: "page-numbers",
    name: "Add Page Numbers",
    description: "Insert page numbers automatically to your PDF",
    icon: "Hash",
    category: "Organize",
    route: "/page-numbers",
    acceptedFormats: [".pdf"],
    outputFormat: "PDF",
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert PDF files to editable Word documents",
    icon: "FileText",
    category: "Convert",
    route: "/pdf-to-word",
    acceptedFormats: [".pdf"],
    outputFormat: "DOCX",
  },
  {
    id: "pdf-to-excel",
    name: "PDF to Excel",
    description: "Extract data from PDFs into Excel spreadsheets",
    icon: "Table",
    category: "Convert",
    route: "/pdf-to-excel",
    acceptedFormats: [".pdf"],
    outputFormat: "XLSX",
  },
  {
    id: "pdf-to-ppt",
    name: "PDF to PowerPoint",
    description: "Turn PDF presentations back into editable slides",
    icon: "Monitor",
    category: "Convert",
    route: "/pdf-to-ppt",
    acceptedFormats: [".pdf"],
    outputFormat: "PPTX",
  },
  {
    id: "office-to-pdf",
    name: "Office to PDF",
    description: "Convert Word, Excel, and PowerPoint files to PDF",
    icon: "FilePlus",
    category: "Convert",
    route: "/office-to-pdf",
    acceptedFormats: [".docx", ".xlsx", ".pptx"],
    outputFormat: "PDF",
  },
  {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    description: "Convert each PDF page into a high-quality JPG image",
    icon: "Image",
    category: "Images",
    route: "/pdf-to-jpg",
    acceptedFormats: [".pdf"],
    outputFormat: "ZIP",
  },
  {
    id: "jpg-to-pdf",
    name: "JPG to PDF",
    description: "Combine images into a single PDF document",
    icon: "Images",
    category: "Images",
    route: "/jpg-to-pdf",
    acceptedFormats: [".jpg", ".jpeg", ".png", ".webp"],
    outputFormat: "PDF",
  },
  {
    id: "extract-images",
    name: "Extract Images",
    description: "Pull all embedded images out of a PDF file",
    icon: "Download",
    category: "Images",
    route: "/extract-images",
    acceptedFormats: [".pdf"],
    outputFormat: "ZIP",
  },
  {
    id: "protect",
    name: "Protect PDF",
    description: "Add password protection to secure your PDF",
    icon: "Lock",
    category: "Security",
    route: "/protect",
    acceptedFormats: [".pdf"],
    outputFormat: "PDF",
  },
  {
    id: "unlock",
    name: "Unlock PDF",
    description: "Remove password protection from a PDF",
    icon: "Unlock",
    category: "Security",
    route: "/unlock",
    acceptedFormats: [".pdf"],
    outputFormat: "PDF",
  },
];

router.get("/tools", (req, res) => {
  res.json(tools);
});

export default router;
