kind = "web"
previewPath = "/"
title = "PDFly"
version = "1.0.0"
id = "artifacts/pdfly"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19667

[services.development]
run = "pnpm --filter @workspace/pdfly run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/pdfly", "run", "build" ]
publicDir = "artifacts/pdfly/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19667"
BASE_PATH = "/"
